### ISSUE TITLE
[Feat] Learning Flutter Plugin (part2) // More detail

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/flutter_biometric#1]
## Describe the new feature<br/>
Biometric flutter plugins are more detailed.

## TODO<br/>
- [ ] Add FragmentActivity Exception (Android/Kotlin part)
- [ ] Add Method Enumeration Class (Android/Kotlin part)
- [ ] Add more prompt [(Addition Document)](https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder)
- [ ] Research communication special types(likes Drawable) between kotlin and dart.
- [ ] Support Array at option argument (authenicate method)
- [ ] Improve OOP (Android/Kotlin part)
- [ ] Improve OOP (Dart)
- [ ] Delete PlatformInterface (no point)

## Addition Context<br/>
This project is a hands-on project for my learning.
